---
# tasks file for mysql_shell_access
- name: Configure mysql credentials for users
  template:
    src: user_my.cnf.j2
    dest: ~{{item.user}}/.my.cnf
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0600
  with_items:
    mysql_shell_access_users